name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: eu-central-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY: travelperktest
  FARGATE_CLUSTER: dev-perks
  FARGATE_SERVICE: my-fargate-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Configure DOCKER authentication
        run: |
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password ${{ secrets.AWS_SECRET_ACCESS_KEY }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com  

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
          
      - name: delete existing task definiton
        run: |
          aws ecs delete-task-definitions --task-definitions arn:aws:ecs:${{ env.AWS_DEFAULT_REGION }}:${{ env.AWS_ACCOUNT_ID }}:task-definition/travelperktest
      
      - name: create new task definiton
        run: |
          aws ecs register-task-definitions --cli-input-json file://create_task_definition.json

      - name: start two new tasks from above task definition
        run: |
          aws ecs run-task --task-definition travelperktest --count 2     
      